# Variable Ranking by Pearson/Linear Correlation Coefficient - LEAF Dataset

In [1]:
import math
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler

In [2]:
leaf_data = np.loadtxt('../Data_USL/leaf.csv',delimiter=',')

In [3]:
leaf_data.shape

(340, 16)

In [4]:
def linear_correlation_coeff(x,y):
    xmean = np.mean(x)
    ymean = np.mean(y)
    stdvx = np.sum((x-xmean)**2)
    stdvy = np.sum((y-ymean)**2)
    r = np.dot(x-xmean,y-ymean)/np.sqrt((stdvx*stdvy))
    return r

In [5]:
loop_end = leaf_data.shape[1]
r_lcc = []
for i in range (1,loop_end):
    r = linear_correlation_coeff(leaf_data[:,0],leaf_data[:,i])
    r_lcc.append(r)
    print('i: ', r_lcc[i-1])

i:  -0.015142016547326376
i:  0.09141460302089634
i:  0.2752101178490783
i:  0.14127524729577043
i:  0.11184290470599254
i:  0.04667831920371106
i:  -0.04976661317047229
i:  -0.04002558235513152
i:  -0.0170480505941396
i:  0.10245321896478979
i:  0.07624645270769874
i:  0.0948852053530928
i:  0.05852012269141438
i:  0.18771684999019722
i:  0.01769003965398185


In [6]:
from scipy.stats import pearsonr
loop_end = leaf_data.shape[1]
r_p = []
for i in range (1,loop_end):
    r, pval = pearsonr(leaf_data[:,0],leaf_data[:,i])
    r_p.append(r)
    print('i: ', r_p[i-1])

i:  -0.01514201654732638
i:  0.09141460302089632
i:  0.27521011784907823
i:  0.1412752472957704
i:  0.11184290470599252
i:  0.046678319203711065
i:  -0.04976661317047228
i:  -0.04002558235513153
i:  -0.017048050594139594
i:  0.10245321896478976
i:  0.07624645270769873
i:  0.09488520535309278
i:  0.05852012269141436
i:  0.18771684999019722
i:  0.017690039653981846


In [7]:
count = 0
for i in range (loop_end-1):
    b = math.isclose(r_p[i], r_lcc[i], abs_tol=0.000001)
    if b == True:
        count += 1
    
if count == loop_end - 1:    
    print("The correlation coefficients calculated by us and by Scipy are EQUAL.")
else:
    print("The correlation coefficients vs Scipy are NOT EQUAL.")

The correlation coefficients calculated by us and by Scipy are EQUAL.


In [8]:
np.set_printoptions(precision=17,suppress=True,edgeitems=16)
corr_coeff_leaf_data = np.corrcoef(leaf_data.transpose())
print("For sake of completeness, we can also compute the correlation\
 matrix with Numpy as follows.\nThe matrix shape is: ",
      np.corrcoef(leaf_data.transpose()).shape)

print("\n\nThe matrix is:\n",corr_coeff_leaf_data)

# WHY TRANSPOSE?

# From the docs: https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html
# numpy.corrcoef(x, y=None,...)
# Parameters: x: array_like
# A 1-D or 2-D array containing multiple variables and observations.
# Each row of x represents a variable.
# Each column is a single observation of all those variables.

For sake of completeness, we can also compute the correlation matrix with Numpy as follows.
The matrix shape is:  (16, 16)


The matrix is:
 [[ 1.                  -0.01514201654732637  0.09141460302089631
   0.27521011784907823  0.14127524729577037  0.11184290470599252
   0.04667831920371095 -0.04976661317047221 -0.04002558235513153
  -0.01704805059413954  0.1024532189647896   0.0762464527076986
   0.0948852053530928   0.05852012269141438  0.18771684999019725
   0.0176900396539819 ]
 [-0.01514201654732637  0.9999999999999999  -0.07677164528704074
  -0.02549034264831938 -0.02772203832821884 -0.07162331500178314
  -0.02521871872505347  0.00412931063626591  0.06501620767914641
   0.06232432212049924 -0.00972467242531314 -0.01266410681958376
   0.00462822148520764  0.01063207126162024 -0.04040705316444876
  -0.03354806139936364]
 [ 0.0914146030208963  -0.07677164528704074  1.
   0.5510688069767617   0.553561341598504    0.3735355974537756
   0.3863318587834139  -0.03608618694427429 -0.274

In [9]:
r_abs_lcc = np.abs(r_lcc.copy())
r_abs_lcc

array([0.01514201654732638, 0.09141460302089634, 0.2752101178490783 ,
       0.14127524729577043, 0.11184290470599254, 0.04667831920371106,
       0.04976661317047229, 0.04002558235513152, 0.0170480505941396 ,
       0.10245321896478979, 0.07624645270769874, 0.0948852053530928 ,
       0.05852012269141438, 0.18771684999019722, 0.01769003965398185])

In [10]:
r_ord_lcc = r_abs_lcc.copy() # copy first, since sort is in-place
r_ord_lcc.sort() 
r_ord_lcc[::-1] # reverse, for descending order

array([0.2752101178490783 , 0.18771684999019722, 0.14127524729577043,
       0.11184290470599254, 0.10245321896478979, 0.0948852053530928 ,
       0.09141460302089634, 0.07624645270769874, 0.05852012269141438,
       0.04976661317047229, 0.04667831920371106, 0.04002558235513152,
       0.01769003965398185, 0.0170480505941396 , 0.01514201654732638])

In [11]:
max_indices = np.argsort(r_abs_lcc) # default is ascending max indices 
max_indices =  max_indices[::-1] # Descending
print("The features of interest are, in descending order of relevance, COLUMNS:\n",
      max_indices+1)

The features of interest are, in descending order of relevance, COLUMNS:
 [ 3 14  4  5 10 12  2 11 13  7  6  8 15  9  1]


# Variable Ranking by Mutual Information - Congressional Voting Records Dataset

In [12]:
cv_df = pd.read_csv('../Data_USL/house-votes-84.data',header=None)

In [13]:
cv_df

0  1  2  3  4  5  6  7  8  9  10 11 12 13 14 15 16
0    republican  n  y  n  y  y  y  n  n  n  y  ?  y  y  y  n  y
1    republican  n  y  n  y  y  y  n  n  n  n  n  y  y  y  n  ?
2      democrat  ?  y  y  ?  y  y  n  n  n  n  y  n  y  y  n  n
3      democrat  n  y  y  n  ?  y  n  n  n  n  y  n  y  n  n  y
4      democrat  y  y  y  n  y  y  n  n  n  n  y  ?  y  y  y  y
..          ... .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..
430  republican  n  n  y  y  y  y  n  n  y  y  n  y  y  y  n  y
431    democrat  n  n  y  n  n  n  y  y  y  y  n  n  n  n  n  y
432  republican  n  ?  n  y  y  y  n  n  n  n  y  y  y  y  n  y
433  republican  n  n  n  y  y  y  ?  ?  ?  ?  n  y  y  y  n  y
434  republican  n  y  n  y  y  y  n  n  n  y  n  y  y  y  ?  n

[435 rows x 17 columns]

In [14]:
cv_df[cv_df[16]=='?'][16]

1      ?
9      ?
11     ?
12     ?
13     ?
      ..
389    ?
390    ?
393    ?
400    ?
425    ?
Name: 16, Length: 104, dtype: object

In [15]:
print("Number of missing values per column:")
print("Column \t\t Number of Missing Values")
for i in range (cv_df.shape[1]):
    print(i,"\t\t\t", cv_df[cv_df[i] == '?'][i].size)

Number of missing values per column:
Column 		 Number of Missing Values
0 			 0
1 			 12
2 			 48
3 			 11
4 			 11
5 			 15
6 			 11
7 			 14
8 			 15
9 			 22
10 			 7
11 			 21
12 			 31
13 			 25
14 			 17
15 			 28
16 			 104


In [16]:
cv_df_mod = cv_df.replace('?',np.nan)

In [17]:
cv_df_mod.iloc[:,0:6:5]

0    5
0    republican    y
1    republican    y
2      democrat    y
3      democrat  NaN
4      democrat    y
..          ...  ...
430  republican    y
431    democrat    n
432  republican    y
433  republican    y
434  republican    y

[435 rows x 2 columns]

In [18]:
tmp = cv_df_mod.iloc[:,0:3:2].dropna()
tmp

0  2
0    republican  y
1    republican  y
2      democrat  y
3      democrat  y
4      democrat  y
..          ... ..
429    democrat  n
430  republican  n
431    democrat  n
433  republican  n
434  republican  y

[387 rows x 2 columns]

In [19]:
n_cnt = tmp[tmp[2] == 'n'][2].size
y_cnt = tmp[2].size - n_cnt
total = y_cnt + n_cnt
orig_size = tmp[2].size

In [20]:
print(n_cnt,y_cnt,total,orig_size)

192 195 387 387


In [21]:
n_cnt_r = tmp[(tmp[2] == 'n') & (tmp[0] == 'republican')][0].size
n_cnt_d = tmp[(tmp[2] == 'n') & (tmp[0] == 'democrat')][0].size
y_cnt_r = tmp[(tmp[2] == 'y') & (tmp[0] == 'republican')][0].size
y_cnt_d = tmp[(tmp[2] == 'y') & (tmp[0] == 'democrat')][0].size
print("N-R: ", n_cnt_r)
print("N-D: ", n_cnt_d)
print("Total N: ", n_cnt)
print("Y-R: ", y_cnt_r)
print("Y-D: ", y_cnt_d)
print("Total Y: ", y_cnt)
print("Total ALL: ", total)

N-R:  73
N-D:  119
Total N:  192
Y-R:  75
Y-D:  120
Total Y:  195
Total ALL:  387


In [22]:
# y in formula is republican/democrat
# x are the various features
p_n_cnt_d = n_cnt_d / total
p_y_cnt_d = y_cnt_d / total
p_n_cnt_r = n_cnt_r / total
p_y_cnt_r = y_cnt_r / total
p_d = (n_cnt_d + y_cnt_d) / total
p_r = (n_cnt_r + y_cnt_r) / total
p_n = (n_cnt_r + n_cnt_d) / total
p_y = (y_cnt_r + y_cnt_d) / total
val =   p_n_cnt_r * np.log(p_n_cnt_r/(p_n*p_r)) + \
        p_y_cnt_r * np.log(p_y_cnt_r/(p_y*p_r)) + \
        p_n_cnt_d * np.log(p_n_cnt_d/(p_n*p_d)) + \
        p_y_cnt_d * np.log(p_y_cnt_d/(p_y*p_d))

val

1.02789605016865e-05

In [23]:
mutual_info_score = []

for i in range (1,cv_df_mod.shape[1]):
    tmp = cv_df_mod.iloc[:,0:i+1:i].dropna()
    #n_cnt = tmp[tmp[i] == 'n'][i].size
    #y_cnt = tmp[i].size - n_cnt
    #total = y_cnt + n_cnt
    total = tmp[i].size
    #print(total)
    n_cnt_r = tmp[(tmp[i] == 'n') & (tmp[0] == 'republican')][0].size
    n_cnt_d = tmp[(tmp[i] == 'n') & (tmp[0] == 'democrat')][0].size
    y_cnt_r = tmp[(tmp[i] == 'y') & (tmp[0] == 'republican')][0].size
    y_cnt_d = tmp[(tmp[i] == 'y') & (tmp[0] == 'democrat')][0].size
    p_n_cnt_d = n_cnt_d / total
    p_y_cnt_d = y_cnt_d / total
    p_n_cnt_r = n_cnt_r / total
    p_y_cnt_r = y_cnt_r / total
    p_d = (n_cnt_d + y_cnt_d) / total
    p_r = (n_cnt_r + y_cnt_r) / total
    p_n = (n_cnt_r + n_cnt_d) / total
    p_y = (y_cnt_r + y_cnt_d) / total
    val =   p_n_cnt_r * np.log(p_n_cnt_r/(p_n*p_r)) + \
            p_y_cnt_r * np.log(p_y_cnt_r/(p_y*p_r)) + \
            p_n_cnt_d * np.log(p_n_cnt_d/(p_n*p_d)) + \
            p_y_cnt_d * np.log(p_y_cnt_d/(p_y*p_d))
    mutual_info_score.append(val)
    
mutual_info_score

[0.08865517473696426,
 1.02789605016865e-05,
 0.3074059064493653,
 0.52550172953441,
 0.3003154356897498,
 0.10209630961100419,
 0.14145155615856664,
 0.23506889728975702,
 0.21820802128994188,
 0.0035179133059576075,
 0.07794198993388148,
 0.27912666374292444,
 0.16750180953165733,
 0.24179475587297855,
 0.1630059710133479,
 0.06461026330242162]

In [24]:
ord_mutual_info_score = mutual_info_score.copy() # copy first, since sort is in-place
ord_mutual_info_score.sort(reverse=True) # reverse, for descending order
ord_mutual_info_score

[0.52550172953441,
 0.3074059064493653,
 0.3003154356897498,
 0.27912666374292444,
 0.24179475587297855,
 0.23506889728975702,
 0.21820802128994188,
 0.16750180953165733,
 0.1630059710133479,
 0.14145155615856664,
 0.10209630961100419,
 0.08865517473696426,
 0.07794198993388148,
 0.06461026330242162,
 0.0035179133059576075,
 1.02789605016865e-05]

In [25]:
max_indices_mi = np.argsort(mutual_info_score) # default is ascending max indices 
max_indices_mi =  max_indices_mi[::-1] # Descending
print("The features of interest are, in descending order of relevance, COLUMNS:\n",
      max_indices_mi+1)

The features of interest are, in descending order of relevance, COLUMNS:
 [ 4  3  5 12 14  8  9 13 15  7  6  1 11 16 10  2]


# PCA - Ionosphere Data

In [26]:
ion_df = pd.read_csv('../Data_USL/ionosphere.data',header=None)

In [27]:
ion_df

0   1        2        3        4        5        6        7        8   \
0     1   0  0.99539 -0.05889  0.85243  0.02306  0.83398 -0.37708  1.00000   
1     1   0  1.00000 -0.18829  0.93035 -0.36156 -0.10868 -0.93597  1.00000   
2     1   0  1.00000 -0.03365  1.00000  0.00485  1.00000 -0.12062  0.88965   
3     1   0  1.00000 -0.45161  1.00000  1.00000  0.71216 -1.00000  0.00000   
4     1   0  1.00000 -0.02401  0.94140  0.06531  0.92106 -0.23255  0.77152   
..   ..  ..      ...      ...      ...      ...      ...      ...      ...   
346   1   0  0.83508  0.08298  0.73739 -0.14706  0.84349 -0.05567  0.90441   
347   1   0  0.95113  0.00419  0.95183 -0.02723  0.93438 -0.01920  0.94590   
348   1   0  0.94701 -0.00034  0.93207 -0.03227  0.95177 -0.03431  0.95584   
349   1   0  0.90608 -0.01657  0.98122 -0.01989  0.95691 -0.03646  0.85746   
350   1   0  0.84710  0.13533  0.73638 -0.06151  0.87873  0.08260  0.88928   

          9   ...       25       26       27       28       29       30  \
0    0.03760  ... -0.51171  0.41078 -0.46168  0.21266 -0.34090  0.42267   
1   -0.04549  ... -0.26569 -0.20468 -0.18401 -0.19040 -0.11593 -0.16626   
2    0.01198  ... -0.40220  0.58984 -0.22145  0.43100 -0.17365  0.60436   
3    0.00000  ...  0.90695  0.51613  1.00000  1.00000 -0.20099  0.25682   
4   -0.16399  ... -0.65158  0.13290 -0.53206  0.02431 -0.62197 -0.05707   
..       ...  ...      ...      ...      ...      ...      ...      ...   
346 -0.04622  ... -0.04202  0.83479  0.00123  1.00000  0.12815  0.86660   
347  0.01606  ...  0.01361  0.93522  0.04925  0.93159  0.08168  0.94066   
348  0.02446  ...  0.03193  0.92489  0.02542  0.92120  0.02242  0.92459   
349  0.00110  ... -0.02099  0.89147 -0.07760  0.82983 -0.17238  0.96022   
350 -0.09139  ... -0.15114  0.81147 -0.04822  0.78207 -0.00703  0.75747   

          31       32       33  34  
0   -0.54487  0.18641 -0.45300   g  
1   -0.06288 -0.13738 -0.02447   b  
2   -0.24180  0.56045 -0.38238   g  
3    1.00000 -0.32382  1.00000   b  
4   -0.59573 -0.04608 -0.65697   g  
..       ...      ...      ...  ..  
346 -0.10714  0.90546 -0.04307   g  
347 -0.00035  0.91483  0.04712   g  
348  0.00442  0.92697 -0.00577   g  
349 -0.03757  0.87403 -0.16243   g  
350 -0.06678  0.85764 -0.06151   g  

[351 rows x 35 columns]

In [28]:
tmp_ion = ion_df.iloc[:,0:34]
ion_data = tmp_ion.to_numpy()

#ion_data

ion_data.shape

(351, 34)

In [32]:
from sklearn.decomposition import PCA

pca = PCA(n_components='mle')
pca.fit(ion_data)
#print(pca.explained_variance_ratio_)
#print(pca.singular_values_)
print(pca.explained_variance_ratio_.shape)
print(type(pca.explained_variance_ratio_))

(33,)
<class 'numpy.ndarray'>
